### ISSUE TITLE
Cкачанные сырые данные

### ISSUE THREAD

**Issue by illusionofchaos** [lovasoa/izbirkom2021#1]
Все 100 тысяч страниц, выгруженных с сайта ЦИК, включая соответсвующие шрифты доступны [здесь](https://github.com/illusionofchaos/IzbirkomRipper/releases/tag/0.0.1) в одном архиве

**Comment by lovasoa** [comment]
Круто ! Вы пробовали расшифровать данные с моим кодом ?

**Comment by lovasoa** [comment]
Я только что посмотрел, мне кажется что они убрали все скремблирование с официального сайта 

![image](https://user-images.githubusercontent.com/552629/134382123-6a34abc7-425f-453d-9b68-9c0dd53f8824.png)

http://www.primorsk.vybory.izbirkom.ru/region/izbirkom?action=show&root=252000008&tvd=4254005265098&vrn=100100067795849&prver=0&pronetvd=null&region=25&sub_region=25&type=242&report_mode=null


вы скачали данные со скремблированием или без ?

**Comment by illusionofchaos** [comment]
> Круто ! Вы пробовали расшифровать данные с моим кодом ?

Сорри за поздний ответ, не заметил уведомление. Я сам только выкачал, деобфускацией не занимался. Вот [тут](https://habr.com/ru/post/579492/) человек описал, как расшифровывал.

> вы скачали данные со скремблированием или без ?

Это только для прошлых выборов результаты в открытом виде, для этого года все обфусцировано.
